{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6f157ad6",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'x3py.itkreg'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mx3py\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mx3py\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mconfig\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ProInit\n\u001b[0;32m----> 3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mx3py\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mitkreg\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ITKregistration\n\u001b[1;32m      6\u001b[0m \u001b[38;5;66;03m#Initialize config and register\u001b[39;00m\n\u001b[1;32m      7\u001b[0m ref_name \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtest_config.json\u001b[39m\u001b[38;5;124m'\u001b[39m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'x3py.itkreg'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_260_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_259_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_263_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_264_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_261_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_268_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_276_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_271_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_265_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_272_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "--- Logging error ---\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "TypeError: not all arguments converted during string formatting\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Call stack:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_277_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_275_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_262_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_267_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_274_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "--- Logging error ---\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "TypeError: not all arguments converted during string formatting\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "Call stack:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "Message: '/local/data/alberto/P-1C_273_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_266_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_269_recReg.h5'\n",
      "Arguments: ('saved',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/logging/__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 725, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1423423/923359649.py\", line 23, in <module>\n",
      "    itkr.CTREG()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 221, in CTREG\n",
      "    distribute_jobs(self.run_regCT,enpoints)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/utils.py\", line 74, in distribute_jobs\n",
      "    with closing(mp.Pool(processes=pool_size)) as p:\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 119, in Pool\n",
      "    return Pool(processes, initializer, initargs, maxtasksperchild,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 215, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 306, in _repopulate_pool\n",
      "    return self._repopulate_pool_static(self._ctx, self.Process,\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 329, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 121, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/context.py\", line 281, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 19, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/popen_fork.py\", line 71, in _launch\n",
      "    code = process_obj._bootstrap(parent_sentinel=child_r)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 125, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/multiprocessing/pool.py\", line 48, in mapstar\n",
      "    return list(map(*args))\n",
      "  File \"/home/beams/AMITTONE/miniconda3/envs/x3py/lib/python3.11/site-packages/x3py/itkreg.py\", line 246, in run_regCT\n",
      "    x3l.info(file_name, \"saved\")\n",
      "Message: '/local/data/alberto/P-1C_270_recReg.h5'\n",
      "Arguments: ('saved',)\n"
     ]
    }
   ],
   "source": [
    "import x3py\n",
    "from x3py.config import ProInit\n",
    "from x3py.itkreg import ITKregistration\n",
    "\n",
    "\n",
    "#Initialize config and register\n",
    "ref_name = 'test_config.json'\n",
    "pI = ProInit(ref_name)\n",
    "\n",
    "extra_args = [ref_name,'TranslationTransform']\n",
    "itkr = ITKregistration(extra_args, pI.ReturnParameters())\n",
    "\n",
    "\n",
    "dic = pI.ReturnParameters()\n",
    "prefix = dic['DataPrefix']\n",
    "epoints = 20\n",
    "\n",
    "\n",
    "#ref, paths = getFolderList(prefix,epoints)\n",
    "#print(ref,paths)\n",
    "\n",
    "#\n",
    "itkr.CTREG()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a272ce9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
